server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:seletivo
    username: itau
    password: todo
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

jwt:
  signing-key:  3378767952393e6267424f2056255a27232f4e34632f51555c345a6126
  expiration: 300

oauth:
  client:
    name: selec@o&t@u
    secret: 2801#It@u!@$SecretPass

management:
  health:
    circuitbreakers:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: logs/client.log

logging:
  file:
    name: logs/client.log

info:
  app:
    name: "controle-tarefa"
    description: "RESTFUL API simples em Java que armazene e atualize tarefas (TODO-LIST API)"
    version: "0.0.1-SNAPSHOT"
    encoding: "UTF-8"
    java:
      version: "11.0.14.1"
    sonar:
      language: "java"
      host:
        url: "${url.sonarqube}"      